FROM neo4j:3.3.7
VOLUME /plugins
RUN apk add --no-cache --quiet \
    bash \
    curl \
    su-exec \
    && cd /plugins \
    && curl --fail --silent --show-error --location --remote-name https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.3.0.4/apoc-3.3.0.4-all.jar 
